<!doctype html>
<html lang="de">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Über Uns</title>
</head>
<#import "../layout.ftlh" as layout>
<@layout.layout>
    <body>
        <h2>Über Uns:</h2>
        <div class="aboutUs">
            <div>
                <h3>Willkommen bei ProxyParcelBox – Ihrer Lösung für eine nahtlose Paketzustellung in der Nachbarschaft!</h3>
                <p>In unserer heutigen, hektischen Welt sind wir oft unterwegs, sei es bei der Arbeit, im Urlaub oder bei sonstigen Verpflichtungen. Das bedeutet, dass viele Pakete ankommen, wenn wir nicht zu Hause sind. Hier kommt ProxyParcelBox ins Spiel. Unsere Plattform wurde speziell für Menschen entwickelt, die ein Paket für ihre Nachbarn entgegengenommen haben und einen einfachen Weg suchen, dieses weiterzuleiten.</p>
            </div>
            <div>
                <h3>Unsere Mission</h3>
                <p>Wir von ProxyParcelBox glauben an die Kraft der Gemeinschaft und Nachbarschaftshilfe. Unsere Mission ist es, die Kommunikation und Zusammenarbeit zwischen Nachbarn zu fördern, indem wir einen einfachen und sicheren Weg bieten, Pakete zu verwalten und zu übergeben.</p>
            </div>
        </div>
    </body>
</@layout.layout>
</html>