<!doctype html>
<html lang="de">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Support</title>
</head>
<#import "../layout.ftlh" as layout>
<@layout.layout>
    <body>
    <h2>Support:</h2>
    <div class="support">
        <p>Willkommen auf der Support-Seite von ProxyParcelBox! Wir sind hier, um Ihnen zu helfen und sicherzustellen, dass Ihre Erfahrung mit unserer Plattform so reibungslos und angenehm wie möglich ist. Unten finden Sie alle notwendigen Informationen und Ressourcen, um Unterstützung zu erhalten.</p>
        <div class="faq">
            <h3>Häufig gestellte Fragen</h3>
            <div>
                <p class="question">Wie gebe ich eine Trackingnummer ein?</p>
                <p>Gehen Sie auf unsere Startseite und geben Sie die Trackingnummer in das dafür vorgesehene Feld ein. Klicken Sie dann auf „Abschicken“, um mit Ihrem Nachbarn zu kommunizieren.</p>
            </div>
            <div>
                <p class="question">Ist die Nutzung von ProxyParcelBox kostenlos?</p>
                <p>Ja, die Nutzung unserer Plattform ist völlig kostenlos.</p>
            </div>
            <div>
                <p class="question">Was mache ich, wenn mein Nachbar nicht antwortet?</p>
                <p>Falls Ihr Nachbar nicht innerhalb von 48 Stunden antwortet, können Sie eine Benachrichtigung erneut senden oder sich an unseren Support wenden.</p>
            </div>
        </div>
        <div class="contact">
            <h3>Kontakt:</h3>
            <p>Schreiben Sie uns eine E-Mail an support@proxyparcelbox.com. Wir bemühen uns, alle Anfragen innerhalb von 24 Stunden zu beantworten.</p>
        </div>
    </div>
    </body>
</@layout.layout>
</html>